name: Build and Release RQPlayer

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build RQPlayer (Windows only)
        run: dotnet publish RQPlayer.csproj -c Release -f net9.0-windows10.0.19041.0 --no-self-contained

      - name: Locate built .msix
        id: locate_msix
        run: |
          $msix = Get-ChildItem -Path "**/AppPackages/*_Test/*.msix" -Recurse | Select-Object -First 1
          echo "MSIX_PATH=$($msix.FullName)" >> $env:GITHUB_ENV

      - name: Upload .msix to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.MSIX_PATH }}
