name: Build and Release RQPlayer

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-msix:
    runs-on: windows-latest

    env:
      Solution_Name: RQPlayer.sln
      Project_Path: RQPlayer.csproj
      Configuration: Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Publicar projeto como MSIX
      run: |
        dotnet publish ${{ env.Project_Path }} -c ${{ env.Configuration }} -f net9.0-windows10.0.19041.0 -p:GenerateAppInstallerFile=false -p:AppxPackage=true -p:AppxBundle=Never -o output/msix

    - name: Create release and upload .msix
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: output/msix/**/*.msix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get version name
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Generate version.json
      run: |
        $url = "https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION }}/RQPlayer.msix"
        $json = @{
          version = "${{ env.VERSION }}"
          changelog = "${{ github.event.head_commit.message }}"
          downloadUrl = $url
        } | ConvertTo-Json -Depth 3
        $json | Out-File -FilePath version.json -Encoding utf8

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@users.noreply.github.com"
    - name: Check and switch to the master branch
      run: |
        git fetch origin master
        git checkout master
    - name: Commit version.json to master
      run: |
        git pull origin master
        git add version.json
        git commit -m "Update version.json to v${{ env.VERSION }}"
        git push origin master
    - name: Rename the MSIX file
      run: |
        $msixFile = Get-ChildItem -Path output/msix/*.msix | Select-Object -First 1
        if ($msixFile) {
          Rename-Item -Path $msixFile.FullName -NewName "RQPlayer.msix"
        } else {
          Write-Error "MSIX file not found. Please check the publish step."
          exit 1
        }
