name: Create Git Tag from version.json

on:
  push:
    branches:
      - master

jobs:
  create_tag:
    name: Create Tag
    runs-on: windows-latest

    permissions:
      contents: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version.json
        id: read_version
        run: |
          VERSION=$(jq -r '.version' version.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag v${{ env.VERSION }} already exists."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Tag v${{ env.VERSION }} does not exist."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Create and push tag
        if: env.exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
